import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Sidebar from "@/components/layout/Sidebar";
import MobileHeader from "@/components/layout/MobileHeader";

// Optional: configure font classes
const geist = Geist({ subsets: ["latin"] });
const geistMono = Geist_Mono({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geist.className} ${geistMono.className} min-h-screen bg-gray-50`}
      >
        <Sidebar />
        <MobileHeader />

        <main className="min-h-screen lg:pl-64 transition-all duration-200">
          <div className="py-20 lg:py-8 px-4 max-w-7xl mx-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
